version: "3.5"
services:
  application:
    build: 
      context: .
    container_name: myzap
    working_dir: /usr/src/app
    ports:
      - ${MYZAP_HOST}:${PORT}:${PORT}
    volumes:
      - ${MYZAP_SESSION_LOCAL}:/usr/src/app/tokens
    networks:
      backend:
        aliases:
          - myzap
networks:
  backend:
    name: myzap_network
